#ifndef H_RADIX_SORT
#define H_RADIX_SORT

/* Generic radix sort generated by Gemini under my guidance.
 * It sorts a vector payload using the vector keys. Note that
 * keys should be a vector of uint32_t or uint64_t. The former
 * for a single rank and the latter for a pair of ranks (packed).
 *
 * For rank assignment, the payload is the sSA and the keys are
 * R1 and R2, packed. KeyType is uint64_t. Pay attention to order
 * when packing: first R2, then R1 (?).
 *      std::vector<uint64_t> keys(N); // pack R1 and R2 here
 *      for(size_t i = 0; i < N; i++)
 *          keys[i] = ((uint64_t)R1[sSA[i]] << 32) | (uint64_t)R2[sSA[i] + h_start];
 *      radix_sort_pairs(keys, sSA, key_buffer, sSA_buffer);
 *
 * For sorting ranks in other contexts, keys are the ranks and
 * KeyType is uint32_t. */
template <typename KeyType, typename PayloadType = uint32_t>
void radix_sort(std::vector<KeyType>& keys, 
                std::vector<KeyType>& key_buffer,
                std::vector<PayloadType>* payload = nullptr,
                std::vector<PayloadType>* payload_buffer = nullptr)
{
    if (keys.empty()) return;

    if (key_buffer.size() < keys.size()) key_buffer.resize(keys.size());

    const int bits_per_pass = 16;
    const int bins = 1 << bits_per_pass;
    const int num_passes = (sizeof(KeyType) * 8) / bits_per_pass;

    KeyType* src_key = keys.data();
    KeyType* dst_key = key_buffer.data();
    PayloadType* src_pay = (payload) ? payload->data() : nullptr;
    PayloadType* dst_pay = (payload_buffer) ? payload_buffer->data() : nullptr;

    size_t counts[bins];

    for (int p = 0; p < num_passes; p++) {
        std::fill(counts, counts + bins, 0);
        int shift = p * bits_per_pass;

        for (size_t i = 0; i < keys.size(); i++)
            counts[(src_key[i] >> shift) & 0xFFFF]++;

        size_t pos = 0;
        for (int i = 0; i < bins; i++) {
            size_t c = counts[i];
            counts[i] = pos;
            pos += c;
        }

        for (size_t i = 0; i < keys.size(); i++) {
            uint32_t bucket = (src_key[i] >> shift) & 0xFFFF;
            uint32_t target = counts[bucket]++;
            dst_key[target] = src_key[i];
            if (dst_pay && src_pay) dst_pay[target] = src_pay[i];
        }

        std::swap(src_key, dst_key);
        std::swap(src_pay, dst_pay);
    }

    if (src_key != keys.data()) {
        std::copy(key_buffer.begin(), key_buffer.end(), keys.begin());
        if (payload && payload_buffer)
            std::copy(payload_buffer->begin(), payload_buffer->end(), payload->begin());
    }
}

#endif
